# Generated by Django 3.0.2 on 2020-02-04 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('price', models.IntegerField()),
                ('category', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=600)),
                ('in_stock', models.BooleanField()),
            ],
        ),
    ]
