# Generated by Django 3.0.3 on 2020-03-23 14:05

import Market.apps.product.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20200317_1458'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImageList',
            fields=[
                ('name', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to=Market.apps.product.models.get_image_path)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='images',
        ),
        migrations.AddField(
            model_name='product',
            name='images',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.ProductImage'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='list',
            field=models.ManyToManyField(blank=True, null=True, to='product.ProductImageList'),
        ),
    ]
