# Generated by Django 3.0.3 on 2020-03-02 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0003_auto_20200302_1235'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstLastName', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=14)),
                ('shippingAddres', models.CharField(max_length=150)),
                ('products', models.ManyToManyField(to='product.Product')),
            ],
        ),
    ]
